import React, { useEffect, useState } from 'react';
import { getProvider } from '../../core/provider';
import { Student, Attendance, ClassInfo, AttendanceStatus } from '../../core/types';
import { Save, Search, Check, X, Clock } from 'lucide-react';

const AttendanceManager: React.FC = () => {
  const [classes, setClasses] = useState<ClassInfo[]>([]);
  const [selectedClassId, setSelectedClassId] = useState<string>('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  
  const [students, setStudents] = useState<Student[]>([]);
  const [attendanceMap, setAttendanceMap] = useState<Record<string, AttendanceStatus>>({});
  const [notesMap, setNotesMap] = useState<Record<string, string>>({});
  
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getProvider().getClasses().then(res => {
        setClasses(res);
        if (res.length > 0) setSelectedClassId(res[0].id);
    });
  }, []);

  useEffect(() => {
    if (selectedClassId) {
        loadData();
    }
  }, [selectedClassId, date]);

  const loadData = async () => {
    setLoading(true);
    const provider = getProvider();
    const [sts, atts] = await Promise.all([
        provider.getStudents(selectedClassId),
        provider.getAttendanceByClassDate(selectedClassId, date)
    ]);
    
    setStudents(sts);
    const attMap: Record<string, AttendanceStatus> = {};
    const nMap: Record<string, string> = {};

    sts.forEach(s => {
        const record = atts.find(a => a.studentId === s.id);
        attMap[s.id] = record ? record.status : 'PRESENT';
        nMap[s.id] = record?.note || '';
    });
    setAttendanceMap(attMap);
    setNotesMap(nMap);
    setLoading(false);
  };

  const handleStatusChange = (studentId: string, status: AttendanceStatus) => {
    setAttendanceMap(prev => ({ ...prev, [studentId]: status }));
  };
  
  const handleNoteChange = (studentId: string, note: string) => {
    setNotesMap(prev => ({ ...prev, [studentId]: note }));
  };

  const handleSave = async () => {
    if (!selectedClassId) return;
    const records: Attendance[] = students.map(s => ({
        id: '', // Generated by provider
        classId: selectedClassId,
        studentId: s.id,
        date,
        status: attendanceMap[s.id] || 'PRESENT',
        note: notesMap[s.id]
    }));
    await getProvider().markAttendance(selectedClassId, date, records);
    alert('Đã lưu điểm danh thành công!');
    loadData();
  };

  return (
    <div className="space-y-6">
       <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 grid grid-cols-1 md:grid-cols-3 gap-6 items-end">
        <div>
            <label className="font-bold text-slate-700 block mb-2">Chọn lớp:</label>
            <select 
                className="w-full border p-2 rounded-lg text-slate-700"
                value={selectedClassId}
                onChange={e => setSelectedClassId(e.target.value)}
            >
                {classes.map(c => <option key={c.id} value={c.id}>{c.className} - {c.homeroomTeacher}</option>)}
            </select>
        </div>
        <div>
            <label className="font-bold text-slate-700 block mb-2">Ngày điểm danh:</label>
            <input 
                type="date" 
                value={date} 
                onChange={e => setDate(e.target.value)}
                className="w-full border p-2 rounded-lg text-slate-700"
            />
        </div>
        <div className="flex justify-end">
            <button 
                onClick={handleSave}
                disabled={loading || students.length === 0}
                className="bg-green-600 text-white px-6 py-2.5 rounded-lg flex items-center gap-2 hover:bg-green-700 transition font-medium disabled:opacity-50"
            >
                <Save size={18} /> Lưu dữ liệu
            </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
        {loading ? (
            <div className="p-12 text-center text-slate-500">Đang tải danh sách học sinh...</div>
        ) : students.length === 0 ? (
            <div className="p-12 text-center text-slate-500">Lớp này chưa có học sinh nào.</div>
        ) : (
            <table className="w-full text-left border-collapse">
            <thead className="bg-slate-50 text-slate-500 text-sm uppercase">
                <tr>
                    <th className="p-4 border-b">Học sinh</th>
                    <th className="p-4 border-b text-center w-24">Có mặt</th>
                    <th className="p-4 border-b text-center w-24">Vắng</th>
                    <th className="p-4 border-b text-center w-24">Muộn</th>
                    <th className="p-4 border-b">Ghi chú</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
                {students.map(s => {
                    const status = attendanceMap[s.id];
                    return (
                        <tr key={s.id} className={`hover:bg-slate-50 transition ${status === 'ABSENT' ? 'bg-red-50' : ''}`}>
                            <td className="p-4">
                                <div className="font-medium text-slate-800">{s.fullName}</div>
                                <div className="text-xs text-slate-400">{s.code}</div>
                            </td>
                            <td className="p-4 text-center">
                                <button 
                                    onClick={() => handleStatusChange(s.id, 'PRESENT')}
                                    className={`p-2 rounded-full ${status === 'PRESENT' ? 'bg-green-100 text-green-700' : 'text-slate-300 hover:bg-slate-100'}`}
                                >
                                    <Check size={20} />
                                </button>
                            </td>
                            <td className="p-4 text-center">
                                <button 
                                    onClick={() => handleStatusChange(s.id, 'ABSENT')}
                                    className={`p-2 rounded-full ${status === 'ABSENT' ? 'bg-red-100 text-red-700' : 'text-slate-300 hover:bg-slate-100'}`}
                                >
                                    <X size={20} />
                                </button>
                            </td>
                            <td className="p-4 text-center">
                                <button 
                                    onClick={() => handleStatusChange(s.id, 'LATE')}
                                    className={`p-2 rounded-full ${status === 'LATE' ? 'bg-orange-100 text-orange-700' : 'text-slate-300 hover:bg-slate-100'}`}
                                >
                                    <Clock size={20} />
                                </button>
                            </td>
                            <td className="p-4">
                                <input 
                                    className="w-full border-b border-slate-200 focus:border-blue-500 focus:outline-none bg-transparent py-1 text-sm"
                                    placeholder="Nhập ghi chú..."
                                    value={notesMap[s.id] || ''}
                                    onChange={e => handleNoteChange(s.id, e.target.value)}
                                />
                            </td>
                        </tr>
                    );
                })}
            </tbody>
            </table>
        )}
      </div>
    </div>
  );
};

export default AttendanceManager;